Accelerate well_segment.create_mask
gazprom-neft/petroflow pull request #3
Opened 2019-10-03 14:58 UTC by cdtn

2019-10-18 15:06 UTC, AlexeyKozhevin commented on petroflow/src/utils.py
> +    period : int
Period in counts of array?

2019-10-18 15:07 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +        period : int, optional
Pixels? Centimeters? Meters? Specify it.

2019-11-18 13:26 UTC, Dimonovez commented on petroflow/src/well_segment.py
> +            filled_mask = fill_nans_around(mask, period)
[interpolate](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html#pandas.DataFrame.interpolate)

2019-11-18 13:47 UTC, Dimonovez commented on petroflow/src/well_segment.py
> +            filled_mask = fill_nans_around(mask, period)
For example:
`mask = mask.interpolate('nearest', limit_direction='both', limit=period)
  filled_mask = mask.interpolate('linear', limit_direction='both', limit_area='outside', limit=period)`

2020-04-15 20:16 UTC, cdtn commented
Since the relevant diff is the one with `int_depth` branch, I suggest using [this comparison](https://github.com/gazprom-neft/petroflow/compare/bf09fc27a7d4e431fee6d8085bcef1650d279a53...812f812214a43c2b1f4d7caa6b44e9891eeb42f3) for changes review.

2020-04-15 21:28 UTC, cdtn commented
Since the relevant diff is the one with `int_depth` branch, I suggest using [this comparison](https://github.com/gazprom-neft/petroflow/compare/bf09fc27a7d4e431fee6d8085bcef1650d279a53...06d856d295df2e08022ea48f8c11f66e55b940d6) for changes review.

2020-04-21 09:05 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
>              will be kept in the mask. Defaults to `None`.
Add a comment that the transformed column (or initial column for `mapping=None`) must be numeric.

2020-04-22 12:55 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
>      def drop_nans(self, logs=None):
`mnemonics`, not `logs`

2020-04-27 21:00 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode='logs', dst='mask',
To unify:
```suggestion
    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
```

2020-04-27 21:01 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +        if mode not in ['core', 'logs']:
```suggestion
        if mode not in ["core", "logs"]:
```

2020-04-27 21:02 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +        bad_values : list of str, optional
`drop` will be better

2020-05-02 20:19 UTC, alexandrkuvaev commented on petroflow/src/utils.py
Delete empty line

2020-05-02 20:29 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +
Delete empty line

2020-05-02 20:29 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +
Delete empty line

2020-05-02 20:31 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            setattr(self, dst + '_index', index)
It is set in the end of `create_mask`, isn't it?

2020-05-02 20:34 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            Values from `src` series to exlude (e.g. [None, np.nan, ' ']).
```suggestion
            Values from `src` series to exclude (e.g. [None, np.nan, ' ']).
```

2020-05-02 20:40 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            src_series.sort_index(level=0, inplace=True)
Don't do it inplace, since it will affect `src`:
```python
>>> df = pd.DataFrame([[1, 2], [0, 4], [5, 3]], columns=["A", "B"], index=[3, 2, 1])
>>> df
   A  B
3  1  2
2  0  4
1  5  3
>>> s = df["A"]
>>> s.index.is_monotonic
False
>>> s.sort_index(level=0, inplace=True)
>>> s
1    5
2    0
3    1
Name: A, dtype: int64
>>> df
   A  B
3  5  2
2  0  4
1  1  3
```

2020-05-02 20:43 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
>          mapping : dict or None
Please, add an option for `mapping` to be a `callable`.

2020-05-02 20:43 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            Mapping to numeric values, required if data in `src[column]`
Why only numeric?

2020-05-02 20:48 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
* Let's unify naming a bit. In almost all (if not every) other methods we have `attr` for a segment attribute and `src` for its column.
* If `mode` is `"logs"`, I'd like to put the results in logs themselves since it will simplify pipelines a lot. Any objections?
* Do we really need `create_index` if we can set a series to `dst` in case of `"core"`?

@AlexeyKozhevin, your thoughts?

2020-05-04 03:09 UTC, cdtn commented on petroflow/src/well_segment.py
> +            insert_value = np.array([mapping[x] for x in uniques])[indexes]
`Series.map` is slower then this custom mapping, when target array is small. Since `WellSegment` attributes with string values (e.g. `'core_lithology'`, `'layers'`) are about 20-80 lines long, it makes sense use custom mapping function.

![photo_2020-05-04_06-07-36](https://user-images.githubusercontent.com/53620809/80933715-953f7f00-8dcd-11ea-8442-df67a911fa8a.jpg)

2020-05-04 03:10 UTC, cdtn commented on petroflow/src/well_segment.py
> +            Mapping to numeric values, required if data in `src[column]`
It's because `numba` can't work with arrays of `object` type. If you see any usecases for non-numeric masks, they can be implemented by either mapping values back after mask creation, or using `fill_intervals` without `@njit`.

2020-05-04 03:11 UTC, cdtn commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
I've implemented the first two suggestions.

As for the third, how about storing an index for our core data from the very beginning? Or will it be too heavy in terms of memory usage?

2020-05-04 11:03 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
@alexandrkuvaev I agree, we can use pd.Series.
I'm not sure if this is really important, because in most cases we just need to make sure that the shape of the mask matches the `core_dl` in the segment, so pixels indices are not important.

2020-05-04 13:43 UTC, cdtn commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
@AlexeyKozhevin do you ever make use of depth info when passing core photos to model?

2020-05-04 13:46 UTC, cdtn commented on petroflow/src/well_segment.py
> +            Mapping to numeric values, required if data in `src[column]`
@AlexeyKozhevin what are your thoughts on non-numeric masks?

2020-05-05 15:10 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
No, but it can be useful when some core propertн dependы on depth.
In that case, yes, we can add depth as an additional channel.

2020-05-05 15:11 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +            Mapping to numeric values, required if data in `src[column]`
I wish we have such an opportunity.

2020-05-06 00:55 UTC, cdtn commented on petroflow/src/well_segment.py
> +    def create_mask(self, src, column, mapping=None, mode="logs", dst="mask",
Core depth index is now stored in `core_index` attribute of `WellSegment`. It's constructed during mask creation, if not exist already.

It is more memory-efficient than storing each mask as a series, since the depth index is the same for all of them in `'core'` mode.

2020-05-06 11:08 UTC, alexandrkuvaev commented on petroflow/src/utils.py
2 blank lines after import

2020-05-06 11:08 UTC, alexandrkuvaev commented on petroflow/src/utils.py
> +def fast_fill_intervals(arr, starts, ends, values):
Revert back to `fill_intervals`.

2020-05-06 11:27 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +                src_values = np.array([mapping[x] for x in uniques])[indices]
```suggestion
            if isinstance(mapping, dict):
                mapping = lambda x, mapping=mapping: mapping.get(x, default)
```
To avoid code duplication and allow for a callable check later on instead of `elif`

2020-05-06 11:42 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            limit *= self.logs_step if mode == 'logs' else self.pixels_per_cm
Please, check that `limit` in `fillna` actually uses index values. As far as I remember, it is already the number of samples to fill.

2020-05-06 11:45 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            mask = pd.Series(mask).fillna(method='ffill', limit=limit).fillna(method='bfill', limit=limit).values
It will fill up holes of up to `2 * limit` length. If it's by design, update the docstring appropriately.

2020-05-06 11:48 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +                    setattr(self, 'core_index', index)
I still think, that storing the `mask` as a `Series` is much more convenient. It will simplify the code a lot and remove the unnecessary `create_core_index` arg.

2020-05-06 11:53 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +        if src_values.dtype.kind in set('buifc'): # if numeric, can use numba
Try switching from `@njit` to `@jit` in `fill_intervals` to avoid this `if` block. But make sure that the performance for integer dtypes is not affected.

2020-05-06 12:53 UTC, cdtn commented on petroflow/src/well_segment.py
> +                    setattr(self, 'core_index', index)
How about creating core depth index when `load_core` is called?

2020-05-06 14:18 UTC, cdtn commented on petroflow/src/well_segment.py
> +            mask = pd.Series(mask).fillna(method='ffill', limit=limit).fillna(method='bfill', limit=limit).values
From docstring:

<pre>limit : int, optional
    If specified, the maximum number of consecutive nan values to fill
    <b>both backward and forward</b> with the closest value that is not nan.</pre>

You think it's not clear enough?

2020-05-06 14:33 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            mask = pd.Series(mask).fillna(method='ffill', limit=limit).fillna(method='bfill', limit=limit).values
Yep, it wasn't clear for me until I read the code.

2020-05-06 14:34 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +                    setattr(self, 'core_index', index)
You'll have to modify other methods (e.g. cropping) to everything work correctly.

2020-05-06 14:59 UTC, cdtn commented on petroflow/src/well_segment.py
> +                src_values = np.array([mapping[x] for x in uniques])[indices]
Usage of default value when mapping by dict will lead to unexpected result, when some key is forgotten in mapping scheme. It better fail with `KeyError`.

How about latest commit solution — `mapping = mapping.get if isinstance(mapping, dict) else mapping`?

2020-05-06 15:05 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +                src_values = np.array([mapping[x] for x in uniques])[indices]
It will return `None` if the key is forgotten, using `default` here looks better.

In fact, I don't see anything wrong with a missing key in the `mapping`, you can even implement the following logic:
```
mapping = lambda x, mapping=mapping: mapping.get(x, x)
```

2020-05-06 15:11 UTC, cdtn commented on petroflow/src/well_segment.py
> +                    setattr(self, 'core_index', index)
Ok than, let's create `core_index` attribute when `create_mask` in `'core'` mode is first called. I think it's still better, than creating several masks (and I suppose you usually want more than one) in form of series, each storing core depth index.

2020-05-06 15:14 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +                    setattr(self, 'core_index', index)
I haven't seen a case, where several masks for core were needed, while memory overhead is negligible. @AlexeyKozhevin, your thoughts?

2020-05-06 15:18 UTC, AlexeyKozhevin commented on petroflow/src/well_segment.py
> +                    setattr(self, 'core_index', index)
Usually, I have only one mask

2020-05-06 15:23 UTC, cdtn commented on petroflow/src/well_segment.py
> +                src_values = np.array([mapping[x] for x in uniques])[indices]
Imagine having a series like `['a', 'a', …, 'a', 'b', 'a', …, 'a', 'a']`. If you wish to map it via dict to `[0, 0, …, 0, 1, 0, …, 0, 0]` and for some reason forget about the `'b'` key (i.e. use `{'a': 0}` as a mapping), than finding this error will take you some time.

Contrary, if you wish not to map some values, you can explicitly define the identity mapping through the dict.

2020-05-07 12:23 UTC, cdtn commented on petroflow/src/well_segment.py
> +        if src_values.dtype.kind in set('buifc'): # if numeric, can use numba
`@jit` and `@njit` performance for numeric dtype is the same.
<img width="794" alt="num" src="https://user-images.githubusercontent.com/53620809/81293518-22a4fc80-9076-11ea-9c86-f911f73feec6.png">
But, surprisingly, `@jit` version is worse for object dtype then non-numba one.
<img width="800" alt="obj" src="https://user-images.githubusercontent.com/53620809/81293512-2173cf80-9076-11ea-8e95-437aa88988cf.png">

2020-05-15 21:55 UTC, cdtn commented
_N.B._ that lengths of `core_dl` and `core_masks` coincide even after segment slicing (with no additional slicing fixes applied).

2020-05-27 18:05 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +        if self._core_masks is not None:
Needs to be preloaded if `_has_file` returns `True`.

2020-05-27 18:07 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +        src_attr : str, from `self.attrs_depth_index`, `self.attrs_fdtd_index`
Revert back to `attr`

2020-05-27 18:07 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +        dst_attr : 'logs' or 'core_masks'
Revert back to `mode` and its description.

2020-05-27 18:10 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +        src_values = map_values(src_series, mapping) if mapping else src_series.values
Move this if inside `map_values`

2020-05-27 18:21 UTC, alexandrkuvaev commented on pylintrc
> +
Move to `FORMAT` section

2020-05-27 18:24 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +        dtype = 'float64' if src_dtype.kind in set('buif') else 'object'
Better choose the minimal `dtype` to represent both values from `src_values` and `default`

2020-05-27 18:26 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            both sides of each non-nan interval. Its boundary values are used
Value, not interval. Also, don't get the following sentence.

2020-05-27 18:28 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            to fill consecutive nan positions. Gaps bigger than `limit` will
Again, `2 * limit`

2020-05-27 18:28 UTC, alexandrkuvaev commented on petroflow/src/well_segment.py
> +            If `dict`, keys are from `src_attr[src]`.
Describe what `dict` does.

2020-06-17 19:24 UTC, cdtn commented on petroflow/src/well_segment.py
> +            both sides of each non-nan interval. Its boundary values are used
Don't get you. Intervals (consisting of values) are padded from sides, if nans are there.

2020-09-03 15:01 UTC, alexandrkuvaev requested changes

2020-09-03 16:16 UTC, alexandrkuvaev approved these changes

2020-09-03 16:17 UTC, merged